apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: student-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/turkardiksha345-oss/Manifest-repo.git
    targetRevision: HEAD
    path: argocd   # ✅ IMPORTANT (your folder)

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true