apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-app-backend
  namespace: default
  labels:
    app: student-app-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-app-backend
  template:
    metadata:
      labels:
        app: student-app-backend
    spec:
      containers:
        - name: backend-container
          image: dikshat1024/easy-crud-backend:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 200m
              memory: 100Mi
            limits:
              cpu: 500m
              memory: 200Mi